ec2_name_prefix: TRAINING
ec2_security_group: insecure_all
ec2_region: us-east-1
ec2_vpc_id: "{{ ec2_regions[ec2_region].vpc }}"
ec2_vpc_subnet_id: "{{ ec2_regions[ec2_region].subnet_id }}"
ec2_key_name: "{{ ec2_regions[ec2_region].key_name }}"
ec2_exact_count: 1
ec2_wait: yes

ec2_lab_node_types:
  - name: node1
    type: openshift-node

  - name: node2
    type: openshift-node

  - name: master
    type: openshift-master

docker_storage_dev_name: /dev/sda2
docker_storage_dev_size: 30
