# --- Lookup tables --- #
# Region specific AMIs, subnets, and VPCs
ec2_regions:
  us-east-1:
    vpc: vpc-06c9a463
    subnet_id: subnet-a2169ed5
    key_name: "{{ ec2_key_name | default('training') }}"
    amis:
      centos7: ami-61bbf104
      centos7-tower: ami-877b9e91
      rhel7: ami-85241def
      rhel7-tower: ami-85241def
      openshift-node: ami-85241def
      openshift-master: ami-85241def

  us-west-1:
    vpc: vpc-ce1f9aab
    subnet_id: subnet-25b9157c
    key_name: "{{ ec2_key_name | default('training') }}"
    amis:
      centos7: ami-af4333cf
      centos7-tower: ami-c04a00a0
      rhel7: ami-f88fc498
      rhel7-tower: ami-f88fc498
      openshift-node: ami-f88fc498
      openshift-master: ami-f88fc498

# Instance types used for lab configurations
ec2_instance_types:

  # Look for owner 309956199498 to find official Red Hat AMIs

  openshift-node:
    ami_id: "{{ ec2_regions[ec2_region].amis['openshift-node'] }}"
    size: t2.medium
    os_type: linux
    disk_space: 20

  openshift-master:
    ami_id: "{{ ec2_regions[ec2_region].amis['openshift-master'] }}"
    size: t2.large
    os_type: linux
    disk_space: 30

# Login names used for SSH connections. These are baked in to the AMIs.
ec2_login_names:
  rhel7-tower: ec2-user
  rhel7: ec2-user
  openshift-node: ec2-user
  openshift-master: ec2-user
  centos7-tower: centos
  centos7: centos
  ubuntu14: ubuntu
  ubuntu16: ubuntu

# Backwards compatability
types: "{{ ec2_lab_node_types }}"
aws_key_name: "{{ ec2_key_name }}"
