common_node_config_options:
  - dest: /etc/ssh/sshd_config
    regexp: '^#?Port'
    line: Port {{ ssh_port | default('22') }}
    validate: sshd -t -f %s

  - dest: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication yes'
    validate: sshd -t -f %s

  - dest: /etc/ssh/sshd_config
    regexp: '^#?UseDNS'
    line: 'UseDNS no'
    validate: sshd -t -f %s

  - dest: /etc/sudoers
    regexp: '^{{ username }}'
    line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

  - dest: /etc/sudoers
    regexp: '^Defaults.*requiretty'
    line: 'Defaults    !requiretty'
    validate: visudo -cf %s

# this should be overridden in extra-vars the vast majority of the time
rhsm_pool_id: 8a85f9833e1404a9013e3cddf99305e6
